import { developmentMockEnabled } from '../config/developmentMock'
import { createDevelopmentMockSnapshot } from '../data/developmentMock'
import type { DemoSessionState, FeedbackPayload, SystemSnapshot } from '../types'

export const initialFeedback: FeedbackPayload = {
  resultStatus: null,
  progressPercent: 0,
  actualDurationMinutes: null,
  obstacleCode: null,
  userNote: '',
  energyChange: '',
  unrealisticPart: '',
  planId: null,
  planItemId: null,
  actionIdentifier: null,
}

function createEmptySnapshot(): SystemSnapshot {
  return {
    id: null,
    userId: '',
    version: 0,
    sourceThreadId: null,
    sourceActionResultId: null,
    currentVector: '等待服务端快照',
    currentStage: '等待同步',
    currentAction: '等待计划裁决',
    realityBoundaries: [],
    effectivePatterns: [],
    hypotheses: [],
    recentRevisions: [],
    userCorrections: [],
    revisionCount: 0,
    createdAt: null,
    updatedAt: null,
  }
}

export function createInitialSession(): DemoSessionState {
  const now = new Date().toISOString()
  const systemSnapshot = developmentMockEnabled
    ? createDevelopmentMockSnapshot(now)
    : createEmptySnapshot()
  const initialSource = developmentMockEnabled ? 'mock' : 'none'

  return {
    schemaVersion: 2,
    currentStep: 'idle',
    serverStep: 'idle',
    isLoading: false,
    apiError: null,
    isOfflineCache: false,
    dataSource: initialSource,
    activeThreadId: null,
    snapshotId: null,
    snapshotVersion: null,
    availableThreads: [],
    activeThread: null,
    uiThreadStatus: '等待校准',
    uiThreadPhase: '等待服务端',
    activeUnderstandingSession: null,
    understandingSessionId: null,
    understandingStatus: 'idle',
    understandingConfirmedAt: null,
    serverUnderstanding: null,
    understandingRequestStatus: 'idle',
    understandingApiError: null,
    understandingSource: initialSource,
    lastSuccessfulUnderstandingAt: null,
    answerMeta: {},
    latestActionResult: null,
    serverSnapshot: null,
    expressionMode: null,
    userInput: '',
    currentAnswerDraft: '',
    understandingAssessmentDraft: null,
    understandingCorrectionDraft: '',
    answers: {},
    submittedAnswers: {},
    currentQuestionIndex: 0,
    currentQuestion: null,
    understanding: null,
    corrections: [],
    currentPlan: null,
    planVersions: [],
    activePlanId: null,
    planRequestStatus: 'idle',
    planApiError: null,
    planSource: initialSource,
    lastSuccessfulPlanAt: null,
    lastViewedPlanId: null,
    planModificationDraft: {
      reason: null,
      userChoice: '',
      expectedImpactAcknowledged: false,
    },
    actionFeedback: { ...initialFeedback },
    actionResultId: null,
    actionResultStatus: null,
    actionResultSubmittedAt: null,
    actionResultRequestStatus: 'idle',
    actionResultApiError: null,
    actionResultSource: initialSource,
    latestSnapshot: null,
    previousSnapshot: null,
    snapshotDiff: null,
    latestActionHypothesis: null,
    systemRevisionSource: initialSource,
    systemRevisionAt: null,
    systemRevision: null,
    activeCorrectionTarget: null,
    correctionType: null,
    correctionDraft: '',
    correctionReason: '',
    correctionDiscontinueConfirmed: false,
    correctionRequestStatus: 'idle',
    correctionApiError: null,
    latestCorrectionId: null,
    latestCorrectionAt: null,
    latestCorrectionResult: null,
    correctionSource: initialSource,
    systemSnapshot,
  }
}
